version:             "3"

networks:
    lbs.net:
        driver:      bridge

services:
    api.commande:
        image:       node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=api.commande.local
        ports:
            - "19080:8080"
        volumes:
            - ./commande_dev:/app/commande_api
        working_dir: /app/commande_api
        command:     npm start
        networks:
            - lbs.net
        links:
            - mysql.commande:dbcom

    api.catalogue:
        image:       node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=api.catalogue.local
        ports:
            - "19081:8080"
        volumes:
            - ./commande_dev:/app/catalogue_api
        working_dir: /app/catalogue_api
        # command:     npm start
        networks:
            - lbs.net
        links:
            - mysql.commande:dbcom

    api.suivie:
        image:       node
        environment:
            - NODE_ENV=dev
            - VHOST_HOSTNAME=api.suivie.local
        ports:
            - "19082:8080"
        volumes:
            - ./commande_dev:/app/suivie_api
        working_dir: /app/suivie_api
        # command:     npm start
        networks:
            - lbs.net
        links:
            - mysql.commande:dbcom

    mysql.commande:
        image:       mariadb:latest
        command:     --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_ROOT_PASSWORD=comroot123
            - MYSQL_USER=command_lbs
            - MYSQL_PASSWORD=command_lbs
            - MYSQL_DATABASE=command_lbs
        ports:
            - "3307:3306"
        networks:
            - lbs.net
        volumes:
            - ./commande_api/sql:/var/sql

    mysql.catalogue:
        image:       mariadb:latest
        command:     --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_ROOT_PASSWORD=comroot123
            - MYSQL_USER=catalogue_lbs
            - MYSQL_PASSWORD=catalogue_lbs
            - MYSQL_DATABASE=catalogue_lbs
        ports:
            - "3308:3306"
        networks:
            - lbs.net
        volumes:
            - ./catalogue_api/sql:/var/sql

    mysql.suivie:
        image:       mariadb:latest
        command:     --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_ROOT_PASSWORD=comroot123
            - MYSQL_USER=suivie_lbs
            - MYSQL_PASSWORD=suivie_lbs
            - MYSQL_DATABASE=suivie_lbs
        ports:
            - "3309:3306"
        networks:
            - lbs.net
        volumes:
            - ./suivie_api/sql:/var/sql

    adminer:
        image:       adminer
        ports:
            - "8080:8080"
        networks:
            - lbs.net
        links:
            - mysql.commande:command
            - mysql.catalogue:catalogue
            - mysql.suivie:suivie
